Fix duplicate index names caused by 63 char limit
AnatolyUss/nmig pull request #96
Opened 2022-04-28 07:06 UTC by simondh

Update IndexAndKeyProcessor.ts
    Postgres limits all object names to 63 chars **nmig** creates index names with:

    `${ conversion._schema }_${ tableName }_${ columnName }_idx`

    Eg `public_accounts_referrerlogin_user_domain_id0_idx` where:

    * _public_ is the schema name
    * _accounts_referrerlogin_ is the table name
    * _user_domain_id_ is the column being indexed
    * Dunno where the _0_ comes from
    * __idx_ is fixed

    This frequently exceeded 63 characters, and when this happens, Postgres simply truncates the name to 63 chars. Now in several cases, the 63 character truncated string was not unique, i.e. the `{ conversion._schema }_${ tableName }_` element was already 63 chars (or some compound indices sharing the same first column). This error showed as:

    `error: duplicate key value violates unique constraint "pg_class_relname_nsp_index"`
    i.e. a unique constraint on the index name itself.

    This change detects index names > 63 chars, and alters then by truncating the created index name to 53 chars then appendix a 6-char UUID fragment, giving a unique index name (very unlikely to have a clash on even 6 UUID chars foir this limited use range)

2022-06-11 07:27 UTC, AnatolyFromPerion requested changes
@simondh 
I initially missed the issue with 63 chars name limit.
Thank you for this PR!

2022-06-11 07:27 UTC, AnatolyFromPerion commented on config/config.json
> +    "uuid_columns_description": [
@simondh 
Here you propose a new feature that not related to this PR's title <code>Fix duplicate index names caused by 63 char limit</code>.
If you'd like to propose a new feature - a separate PR should be submitted (good Git practice).

Regarding your possible proposal:
In general, there is a customizable data types configuration <code>nmig/config/data_types_map.json</code>.
If we want to introduce PG-specific types - I would say that something like <code>nmig/config/extra_data_types_map.json</code> needed.
Just as it is with <code>config.json</code> for basic configuration, and <code>extra_config.json</code> for "advanced" configuration.
Besides that, you initialize <code>_uuidColumns</code> in <code>nmig/src/Conversion.ts</code>, but this code doesn't do actual types conversion anyway...

2022-06-11 07:27 UTC, AnatolyFromPerion commented on src/Conversion.ts
> +    /**
@simondh 
Please, mind my comments above regarding <code>_uuidColumns</code>

2022-06-11 07:27 UTC, AnatolyFromPerion commented on src/IndexAndKeyProcessor.ts
> +            // sqlAddIndex = `CREATE ${ (objPgIndices[index].is_unique ? 'UNIQUE ' : '') }INDEX "${ conversion._schema }_${ tableName }_${ columnName }_idx"
@simondh Please, don't leave commented pieces of code (line 97).

2022-06-11 07:27 UTC, AnatolyFromPerion commented on src/IndexAndKeyProcessor.ts
> +            let index_name = `${ conversion._schema }_${ tableName }_${ columnName }_idx`;
@simondh 
Following is not critically important, but:
1. Could you camel-case variables, as all variables in Nmig are camel-cased? (<code> index_name</code> and <code>uuid_tag</code>)
2. Could you remove <code>console.log</code>, please? (line 93)

2022-07-21 09:20 UTC, closed without merging

2022-07-21 09:23 UTC, AnatolyFromPerion commented
@simondh
Closing this p.r. as the patch is implemented in separate branch.
Thank you very much for pointing out this issue!

2022-07-25 09:14 UTC, simondh commented
OK thanks
Simon Hewitt
(+44) 07799 381001



On Thu, 21 Jul 2022 at 10:23, Anatoly Khaytovich ***@***.***>
wrote:

> @simondh <https://github.com/simondh>
> Closing this p.r. as the patch is implemented in separate branch.
> Thank you very much for pointing out this issue!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AnatolyUss/nmig/pull/96#issuecomment-1191254265>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAW7X7YDPUJ6JZLU2SCKHTVVEJJZANCNFSM5URMLMHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>